### ISSUE TITLE
Update the call to use /api and not apis/ to work with the IMS Operations API for v1 zowe conformance

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/zowe-cli-ims-plugin#23]
Currently the CLI request goes against a REST call with `apis` in the URL, e.g.
```
Resource:  /ims/apis/v1/TEST/region?dc=true&region=true
```
The IMS Operations API for v1 Zowe conformance has the path with `api`.  

This issue is for the CLI to be updated to go against the `api` URL.

**Comment by zFernand0** [comment]
Fixed in:
- https://github.com/zowe/zowe-cli-ims-plugin/pull/24
