### ISSUE TITLE
Help Text: zowe ims query region help may need updated

### ISSUE THREAD

**Issue by zFernand0** [zowe/zowe-cli-ims-plugin#27]
**Current state**

```
 - Query information for regions on route IMS1:
      $ zowe ims query region "IMS1"
```

**Suggested change**

```
 - Query information for regions on route IMS1:
      $ zowe ims query region --route "IMS1"
```

Note: This may apply to other examples within the same action (`query`)

UX question:
- Should route be converted to a positional argument instead of a command option?

**Comment by awharn** [comment]
The IMS Plug-in has been deprecated and will not be receiving any additional fixes / enhancements.
