### ISSUE TITLE
zowe ims query program results in HWSP1140E message in IMS Connect AS

### ISSUE THREAD

**Issue by CRHarriss** [zowe/zowe-cli-ims-plugin#50]
Trying to use zowe ims query program "xxx" which fails with ECONNRESET
I checked ip address and port and IMSplex for my IMS sysytem and all look Ok.

In the HWS (ICON) AS messages, I see this: 

HWSP1440E INVALID LENGTH SPECIFIED IN MESSAGE PREFIX; L=369295617

Looks like the length has either not been set or has an invalid value 

I am using zowe ims plugin as follows:  

pluginName: @zowe/ims-for-zowe-cli
package: @zowe/ims-for-zowe-cli@zowe-v2-lts
version: 3.0.0
registry: https://registry.npmjs.org/ 

Is it possible to set the length or is there a bug in the plugin?

**Comment by CRHarriss** [comment]
Also adding output from VSCode terminal   - command sits / spins at 0% until I cancel it

![image](https://user-images.githubusercontent.com/73721809/175029732-8251a961-2373-4152-ac44-04f55daed5b3.png)

**Comment by awharn** [comment]
The IMS Plug-in has been deprecated and will not be receiving any additional fixes / enhancements.
