### ISSUE TITLE
Zowe v3: `@zowe/ims-for-zowe-cli` should use the IBM Admin Foundation APIs

### ISSUE THREAD

**Issue by zFernand0** [zowe/zowe-cli-ims-plugin#54]
Suggestion: 
- Implement in a vNext branch for a 4.0.0 version of the plug-in

More information:
- [Using IMS Administration Foundation](https://www.ibm.com/docs/en/umsfz/1.1.0?topic=110-using-ims-administration-foundation)

**Comment by awharn** [comment]
IMS Plug-in has been deprecated and will not have a V3 release.
