### ISSUE TITLE
Archive this repository and remove the `@zowe/ims-for-zowe-cli` package from npm

### ISSUE THREAD

**Issue by adam-wolfe** [zowe/zowe-cli-ims-plugin#63]
Given that this plug-in is no longer functional, the Zowe community has agreed to archive this repository and remove the plug-in from npm.

**Comment by JTonda** [comment]
Update the readme and mark the package as deprecated.

**Comment by awharn** [comment]
Readme updated, package is deprecated on both NPM and Zowe's JFrog Artifactory. #66 #65
